version: "3.9"
services:
  networks:
    roboshop:
      driver: bridge
  web:
    image: web:v1
    container_name: web
    depends_on:
    - catalouge
  mongodb:
   image: mongodb:v1
   container_name: mongodb
  catalouge:
    image: catalouge:v1
    container_name: catalouge
    depends_on:
    - mongodb


